version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    networks:
      - my_bridge_network

  k6:
    image: loadimpact/k6
    volumes:
      - ./k6-script-register.js:/k6-script.js
    networks:
      - my_bridge_network
    depends_on:
      - flask_app
    entrypoint: ["k6", "run", "/k6-script.js"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  my_bridge_network:
    driver: bridge
