name: k6 Performance Testing

on:
 push:
 pull_request:
 workflow_dispatch:

jobs:
 k6-test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-python@v2
     with:
       python-version: '3.9'

   - name: Install dependencies
     run: |
       python -m venv venv
       source venv/bin/activate
       pip install -r performance-tests/Soar_Test/requirements.txt

   - name: Copy files  
     run: |
       cp performance-tests/Soar_Test/schema.sql .
       cp performance-tests/Soar_Test/database.db .

   - name: Create database
     run: |
       source venv/bin/activate
       python performance-tests/Soar_Test/db_init.py

   - name: Start Flask app
     run: |
       source venv/bin/activate
       nohup python performance-tests/Soar_Test/task.py > flask.log 2>&1 &
       sleep 5
       echo "FLASK_URL=$(grep -o 'http://[0-9.]*:[0-9]*' flask.log)" >> $GITHUB_ENV

   - name: Install k6
     run: |
       curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
       echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
       sudo apt-get update
       sudo apt-get install k6

   - name: Install Node.js and reporter
     uses: actions/setup-node@v2
     with:
       node-version: '14'
   - run: sudo npm install -g k6-html-reporter

   - name: Run Load Test - Registration
     env:
      K6_WEB_DASHBOARD: "true"
      K6_WEB_DASHBOARD_EXPORT: "k6-results/dashboard-report.html"
     run: |
        mkdir -p k6-results
        k6 run --out html=k6-results/html-report/index.html performance-tests/Soar_Test/k6-script-register.js

#   - name: Run Stress Test - Login
#     run: |
#        k6 run -e FLASK_URL=$FLASK_URL performance-tests/Soar_Test/k6-script-login.js --out json=k6-results/login-results.json --summary-export=k6-results/login-summary.json

#   - name: Run BDD Test
#     run: |
#        k6 run -e FLASK_URL=$FLASK_URL performance-tests/Soar_Test/k6-script-bdd.js --out json=k6-results/bdd-results.json --summary-export=k6-results/bdd-summary.json


   - name: Upload Results
     uses: actions/upload-artifact@v3
     with:
       name: k6-test-results
       path: k6-results/dashboard-report.html