name: k6 Performance Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r performance-tests/Soar_Test/requirements.txt

    - name: Start Flask app
      run: |
        source venv/bin/activate
        nohup python performance-tests/Soar_Test/task.py &

    - name: Add k6 repository and install k6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 33C235A34C46AA3FFB293709A328C3A2C3C45C06
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run k6 script
      run: k6 run performance-tests/Soar_Test/k6-script-register.js

    - name: Display k6 logs
      run: docker-compose logs k6

    - name: Upload k6 results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: k6-results
        path: /path/to/k6/results